### ISSUE TITLE
Will there be a changelog file?

### ISSUE THREAD

**Issue by EdricChan03** [jvandemo/copy-github-labels#10]
Will there be a changelog file for new versions of this library? This can be vital especially for breaking changes from commits or PRs.

For example, my PR #9 changes the `user` property to `owner`, as well as updating the library to use the (no longer) new `@octokit/rest` library as `github` has been marked as deprecated.

**Comment by OpticFusion1** [comment]
Hey, if you could re-make this issue on my [fork](https://github.com/OpticFusion1/copy-github-labels/) that would be nice. This project's dead, and having these issues on my fork will make things easier on me :)
