### ISSUE TITLE
Using copyGitHubLabels.copy() deletes source labels

### ISSUE THREAD

**Issue by slattery** [jvandemo/copy-github-labels#2]
The labels from source did get instantiated on dest, but dest now does not have them anymore.  (It's more like mv-github-labels...)   I can't see how this module could be responsible, but  since there is so little going on I wonder if anyone else has this problem.   

i looked at github getIssueLabels and don't see anything there yet either.

These are private repos if that makes any difference.

```js
var copyGitHubLabels = require('copy-github-labels')();

copyGitHubLabels.authenticate({
	type: "oauth",
  token: "TOKEN"
});

var src = process.argv[2], dst = process.argv[3];

copyGitHubLabels.copy(src, dst, function (err, label){
  if(err){
    return console.log('Could not copy label: ' + err);
  }
  console.log('Label copied successfully: ' + label)
});
```

```sh
node copylabels.js source/repo dest/repo
Label copied successfully: [object Object]
Label copied successfully: [object Object]
...
```

**Comment by jvandemo** [comment]
Hi @slattery, I haven't seen this behavior yet.

I assume you mean that the labels disappeared from the *source* repository after copying.

In essence, the module reads the labels from the source repository, loops over them and creates a new label with the same contents in the destination repository.

It should indeed not remove any label at all.

Are you able to reproduce this?

Thanks!

**Comment by slattery** [comment]
Apologies:  We must disregard.   Upon trying to replicate -- I couldn't because it didn't happen the first time.    User error between web view and CLI.    Thank you for such a quick response.

**Comment by slattery** [comment]
Closing, this never was an issue with this module.

**Comment by jvandemo** [comment]
Hi @slattery, that's great news!

Thanks for the confirmation and thanks for evaluating the module.
