### ISSUE TITLE
CLI version would be great

### ISSUE THREAD

**Issue by ctaepper** [jvandemo/copy-github-labels#5]
install module gloabel and provide something like
```bash
$ github-copy-label <from-repo> <to-repo>
```

**Comment by jvandemo** [comment]
@ctaepper &mdash; Agreed, great idea. Would be very convenient indeed.

I will write one as a separate module (to keep dependencies separated) and report back here when it's ready.

Thanks for the suggestion!

**Comment by jvandemo** [comment]
@ctaepper &mdash; The CLI is available here:

https://github.com/jvandemo/copy-github-labels-cli

Feel free to try it out. Thanks for your feedback!

**Comment by ctaepper** [comment]
it works :+1:

**Comment by jvandemo** [comment]
@ctaepper &mdash; Super, great to hear. Thanks for sharing!
