### ISSUE TITLE
Labels Description

### ISSUE THREAD

**Issue by FMCalisto** [jvandemo/copy-github-labels#8]
GitHub already supports [Labels Description](https://github.com/blog/2505-label-improvements-emoji-descriptions-and-more). It might be a good idea to support it.

**Comment by jvandemo** [comment]
@FMCalisto &mdash; Agree, would you be interested in creating a PR? Thanks! 👍

**Comment by Chan4077** [comment]
@jvandemo I've been trying to work on this. I'll send a PR soon if all goes well.

**Comment by FMCalisto** [comment]
I just saw both answers today, sorry @jvandemo and @Chan4077. Yes, I am interested, however not having much time right now.

@Chan4077 did you sent the PR already?

**Comment by Chan4077** [comment]
@FMCalisto The PR is still open, but I don't get what @jvandemo is asking for. However, I also haven't got much time lately to view what he requested for.

**Comment by FMCalisto** [comment]
@Chan4077 I think the idea is just to add also the copy of the **Labels Description**.

**Comment by EdricChan03** [comment]
@jvandemo Thanks for merging the outstanding PR!
